apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cyberphysicalapplications.test.dev
spec:
  scope: Namespaced
  group: test.dev
  names:
    kind: CyberPhysicalApplication
    plural: cyberphysicalapplications
    singular: cyberphysicalapplication
    shortNames:
      - cpa
      - cpas
      - cyberphysicalapp
      - cyberphysicalapps
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                migrate:
                  type: boolean
                mirrorTime:
                  type: number
                source:
                  type: string
                twinType:
                  type: string
                  enum:
                    - "simple"
                    - "composed"
                twinOf:
                  type: array
                  x-kubernetes-validations:
                    - rule: "size(self) >= 1"
                  items:
                    type: string
                requirements:
                  type: object
                  properties:
                    preferredAffinity:
                      type: string
                    odte:
                      type: number
                deployments:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        enum:
                          - "Kubernetes"
                      affinity:
                        type: string
                      configs:
                        type: array
                        items: 
                          type: object
                          properties:
                            apiVersion:
                              type: string
                            kind:
                              type: string
                            metadata:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
                            spec:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
                            status:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
            status:
              x-kubernetes-preserve-unknown-fields: true
