apiVersion: test.dev/v1
kind: CyberPhysicalApplication
metadata:
  name: "cpa-1"
spec:
  # debug migrazione
  migrate: false
  mirrorTime: 60
  source: ""
  twinType: "simple"
  twinOf: 
   - "led_1"
  requirements:
    preferredAffinity: "mec"
    odte: 0.8
  deployments:
    - type: "Kubernetes"
      affinity: "edge"
      configs:
        - apiVersion: apps/v1
          kind: Deployment
          metadata:
            namespace: default
            name: dt-1-deployment-edge
            labels:
              app: dt-1-edge
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: dt-1-edge
            template:
              metadata:
                labels:
                  app: dt-1-edge
                annotations:
                  # prometheusUrl: "http://prometheus-service.istio-system.svc.cluster.local:9090"
                  prometheusUrl: "http://localhost:30080"
                  prometheus.io/scrape: "true"
                  prometheus.io/port: "8001"
                  prometheus.io/path: "/metrics"
              spec:
                volumes:
                  - name: dump-dt
                    nfs:
                      server: nfs-server-1.test
                      path: /exports
                      readOnly: no
                containers:
                - name: dt-1-edge
                  image: rssgai/dt-flask:massive-dump-rsync-v1
                  ports:
                  - containerPort: 8001
                  volumeMounts:
                    - name: dump-dt
                      mountPath: /var/tmp/dt_data
                  env:
                    - name: MQTT_BROKER
                      value: mosquitto-service.default.svc.cluster.local
                    - name: MQTT_PORT
                      value: "1883"
                    - name: MQTT_TOPIC
                      value: factory_1
                    - name: DUMP_PATH_FILE
                      value: /var/tmp/dt_data/dump.json
                initContainers:
                - name: rsync-init
                  image: rssgai/rsync-util:v2
                  volumeMounts:
                    - name: dump-dt
                      mountPath: /var/tmp/dt_data

        - apiVersion: v1
          kind: Service
          metadata:
            namespace: default
            name: dt-1-service-edge
          spec:
            selector:
              app: dt-1-edge
            ports:
              - name: http
                port: 8001
                targetPort: 8001
              - name: rsyncd
                port: 873
                targetPort: 873
            type: NodePort
    
    - type: "Kubernetes"
      affinity: "mec"
      configs:
        - apiVersion: apps/v1
          kind: Deployment
          metadata:
            namespace: default
            name: dt-1-deployment-mec
            labels:
              app: dt-1-mec
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: dt-1-mec
            template:
              metadata:
                labels:
                  app: dt-1-mec
                annotations:
                  # prometheusUrl: "http://prometheus-service.istio-system.svc.cluster.local:9090"
                  prometheusUrl: "http://localhost:30080"
                  prometheus.io/scrape: "true"
                  prometheus.io/port: "8001"
                  prometheus.io/path: "/metrics"
              spec:
                volumes:
                  - name: dump-dt
                    nfs:
                      server: nfs-server-2.test
                      path: /exports
                      readOnly: no
                containers:
                - name: dt-1-mec
                  image: rssgai/dt-flask:massive-dump-rsync-v1
                  ports:
                  - containerPort: 8001
                  volumeMounts:
                    - name: dump-dt
                      mountPath: /var/tmp/dt_data
                  env:
                    - name: MQTT_BROKER
                      value: mosquitto-service.default.svc.cluster.local
                    - name: MQTT_PORT
                      value: "1883"
                    - name: MQTT_TOPIC
                      value: factory_1
                    - name: DUMP_PATH_FILE
                      value: /var/tmp/dt_data/dump.json
                initContainers:
                - name: rsync-init
                  image: rssgai/rsync-util:v2
                  volumeMounts:
                    - name: dump-dt
                      mountPath: /var/tmp/dt_data

        - apiVersion: v1
          kind: Service
          metadata:
            namespace: default
            name: dt-1-service-mec
          spec:
            selector:
              app: dt-1-mec
            ports:
              - name: http
                port: 8001
                targetPort: 8001
              - name: rsyncd
                port: 873
                targetPort: 873
            type: NodePort
