apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: dt-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: dt-1
      protocol: HTTP
    hosts:
    - "*"
