apiVersion: v1
kind: PersistentVolume
metadata:
  name: dt-dump-test-pv
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: nfs-server.test
    path: /exports